disabled_rules:
  - trailing_whitespace
line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
identifier_name:
  excluded:
    - id
    - url
    - tv
